### ISSUE TITLE
High-level API design

### ISSUE THREAD

**Issue by iranroman** [iranroman/SELD-data-generator#16]
@ChrisIck @adrianSRoman @beasteers Let's use this issue to discuss the high-level API design. 

By high-level I mean the "default" and/or "off-the-shelf" and/or "plug-and-play" use. 

Looking at [Scaper as an example](https://scaper.readthedocs.io/en/latest/tutorial.html), we see that it expects a list of background and foreground files. 

FOREGROUND: I agree that we should let the users spatialize specific sound events in files they have and want. However, I think we should also have a set of "default" sound event classes, such as the [AudioSet ontology](https://research.google.com/audioset/ontology/index.html). things to consider: what are the implications of using (an)echoic sound samples?

BACKGROUND: In our case, specific rooms may have specific background files, so we should use those. Should the user be able to specify background files? where in space should they be placed (i.e. will location overlap with dynamic sound sources)?

Other default settings (that the user could change):
- clip duration: 60 seconds by default
- total number of clips: 100
- clips split: 80% train, 10% val, 10% test
- unique and predefined rooms and sound event clips in each split (mostly for reproducibility and consistency with DCASE task 3)
- annotations generated: following [DCASE Task 3 2023 format](https://dcase.community/challenge2023/task-sound-event-localization-and-detection-evaluated-in-real-spatial-sound-scenes#reference-labels-directions-of-arrival-and-source-distances)

I think our generator should simply "work" via a command like:

```
python main.py
```

And generate sound scapes that allow for reproduction of results using the DCASE task 3 baseline model.

The user could also specify specific temporal and spatial densities of events (how?), as well as trajectories (how???) they follow. We could borrow all other ideas from [Scaper](https://scaper.readthedocs.io/en/latest/tutorial.html) to allow the user to craft very custom sound scapes.

Thoughts? What am I missing?

**Comment by ChrisIck** [comment]
Discussion moved to #17
